# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family      Fira Code
# font_family  JetBrains Mono
font_size    14.0
# modify_font  cell_width -1px
# modify_font  cell_height 10px
# modify_font  underline_position     5
# modify_font  strikethrough_position 5

#: Color scheme {{{

# include themes/catppuccin/mocha.conf
# include themes/catppuccin/macchiato.conf
include themes/tokyo_night/night.conf

background_opacity 0.9
background_blur 20
hide_window_decorations titlebar-only

#: }}}

#: Cursor {{{

cursor none
cursor_blink_interval -1 ease-in-out

cursor_trail 1
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 10

#: }}}

#: Scrollback {{{

scrollback_lines -1
scrollback_fill_enlarged_window yes

#: }}}


#: Mouse {{{

# url_color #0087bd
# url_style curly

mouse_hide_wait 3.0
url_prefixes file ftp ftps git http https mailto sftp ssh
select_by_word_characters @-./_~?&=%+#

#: }}}

#: Performance tuning {{{

input_delay 0
sync_to_monitor no

#: }}}


#: Window layout {{{

remember_window_size yes
# initial_window_width  1080
# initial_window_height 720

enabled_layouts splits, stack
confirm_os_window_close -1
#: }}}


#: Tab bar {{{

tab_bar_style powerline
tab_powerline_style round

#: }}}


#: OS specific tweaks {{{

macos_option_as_alt yes
macos_quit_when_last_window_closed yes
macos_show_window_title_in window
macos_colorspace displayp3
text_composition_strategy 1.2 20

#: }}}

#: Keyboard shortcuts {{{

clear_all_shortcuts yes

include mappings.conf
# include mappings.tmux.conf

#: }}}

#: Clipboard {{{

strip_trailing_spaces always
map cmd+c        copy_to_clipboard
map cmd+v        paste_from_clipboard
map shift+cmd+v  paste_from_selection

#: }}}

#: Window management {{{

map cmd+q quit
map cmd+n new_os_window

#: }}}


#: Font sizes {{{

map cmd+equal  change_font_size all +1.0
map cmd+minus  change_font_size all -1.0
map cmd+0      change_font_size all 0

#: }}}

#: Select and act on visible text {{{

map cmd+o        open_url_with_hints
map cmd+l        kitten hints --type line --program -
map cmd+p        kitten hints --type path --program -
map shift+cmd+p  kitten hints --type path

#: }}}

#: Miscellaneous {{{

map cmd+,          edit_config_file
map cmd+backspace  send_text all \u17
map alt+backspace  send_text all \x17
map shift+cmd+/    show_last_command_output

#: }}}

