#: Window {{{
map cmd+w close_window
map cmd+ctrl+- launch --location=hsplit --cwd=current
map cmd+ctrl+\ launch --location=vsplit --cwd=current

map shift+cmd+h neighboring_window left
map shift+cmd+j neighboring_window down
map shift+cmd+k neighboring_window up
map shift+cmd+l neighboring_window right

map cmd+ctrl+h move_window left
map cmd+ctrl+j move_window down
map cmd+ctrl+k move_window up
map cmd+ctrl+l move_window right

map cmd+enter toggle_layout stack

map cmd+up kitten resize_window.py top
map cmd+down kitten resize_window.py bottom
map cmd+left kitten resize_window.py left
map cmd+right kitten resize_window.py right

#: }}}

#: Tab {{{

map cmd+t   new_tab
map shift+cmd+w  close_tab
map cmd+r  set_tab_title

map shift+cmd+[      previous_tab
map shift+cmd+]      next_tab

map cmd+ctrl+[  move_tab_backward
map cmd+ctrl+]  move_tab_forward

map cmd+1  goto_tab 1
map cmd+2  goto_tab 2
map cmd+3  goto_tab 3
map cmd+4  goto_tab 4
map cmd+5  goto_tab 5
map cmd+6  goto_tab 6
map cmd+7  goto_tab 7
map cmd+8  goto_tab 8
map cmd+9  goto_tab 9

#: }}}

