
# shell /opt/homebrew/bin/tmux new-session -A -s main

# tmux {{{

#: pane {{{

# map cmd+w      combine : send_key ctrl+a : send_key x
map cmd+ctrl+- combine : send_key ctrl+a : send_key -
map cmd+ctrl+\ combine : send_key ctrl+a : send_key \

# map cmd+ctrl+h send_text \x01H
# map cmd+ctrl+j send_text \x01J
# map cmd+ctrl+k send_text \x01K
# map cmd+ctrl+l send_text \x01L

map cmd+ctrl+enter combine : send_key ctrl+a : send_key z

#: }}}

#: window {{{

map cmd+t       combine : send_key ctrl+a : send_key c
# map cmd+shift+w combine : send_key ctrl+a : send_text X
map cmd+r       combine : send_key ctrl+a : send_key r

map shift+cmd+[ combine : send_key ctrl+a : send_key [
map shift+cmd+] combine : send_key ctrl+a : send_key ]

map cmd+ctrl+[  combine : send_key ctrl+a : send_key {
map cmd+ctrl+]  combine : send_key ctrl+a : send_key }

map cmd+1       combine : send_key ctrl+a : send_key 1
map cmd+2       combine : send_key ctrl+a : send_key 2
map cmd+3       combine : send_key ctrl+a : send_key 3
map cmd+4       combine : send_key ctrl+a : send_key 4
map cmd+5       combine : send_key ctrl+a : send_key 5
map cmd+6       combine : send_key ctrl+a : send_key 6
map cmd+7       combine : send_key ctrl+a : send_key 7
map cmd+8       combine : send_key ctrl+a : send_key 8
map cmd+9       combine : send_key ctrl+a : send_key 9

#: }}}

