# general {{{
set-option -g default-terminal "tmux-256color"
unbind-key C-b
set-option -g prefix C-a

# Start windows and panes at 1
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on

set-option -g mouse on
set-option -g focus-events on
set-option -g escape-time 0
set-option -g repeat-time 0
set-option -g mode-keys vi

#}}}

#: window {{{
bind-key c new-window
bind-key C new-window -c "#{pane_current_path}"
bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"

bind-key -r [ previous-window
bind-key -r ] next-window
bind-key -r '{' swap-window -d -t -1
bind-key -r '}' swap-window -d -t +1
#}}}

# is_vim="ps -o state=,tty=,comm= | grep -iqE '^[^TXZ ]+ +#{s|/dev/||:pane_tty}\s+(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

# pane {{{
# Mac Mission Control conflicts
# bind-key -n C-Up if-shell "$is_vim" "send-keys C-Up"  "resize-pane -U 5"
# bind-key -n C-Down if-shell "$is_vim" "send-keys C-Down"  "resize-pane -D 5"
# bind-key -n C-Left if-shell "$is_vim" "send-keys C-Left"  "resize-pane -L 5"
# bind-key -n C-Right if-shell "$is_vim" "send-keys C-Right"  "resize-pane -R 5"
#
bind-key -n C-Up resize-pane -U 5
bind-key -n C-Down resize-pane -D 5
bind-key -n C-Left resize-pane -L 5
bind-key -n C-Right resize-pane -R 5

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H "select-pane -m; select-pane -L; swap-pane; select-pane -L; select-pane -M"
bind J "select-pane -m; select-pane -D; swap-pane; select-pane -D; select-pane -M"
bind K "select-pane -m; select-pane -U; swap-pane; select-pane -U; select-pane -M"
bind L "select-pane -m; select-pane -R; swap-pane; select-pane -R; select-pane -M"
#}}}


# visual mode {{{
bind-key Escape copy-mode
bind-key -T copy-mode-vi K send-keys -N 5 -X cursor-up
bind-key -T copy-mode-vi J send-keys -N 5 -X cursor-down
bind-key -T copy-mode-vi H send-keys -X start-of-line
bind-key -T copy-mode-vi L send-keys -X end-of-line
bind-key -T copy-mode-vi Y send-keys -X copy-end-of-line
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
#}}}

# Kill pane/window/session
bind-key x kill-pane
bind-key X confirm-before -p "kill-window #W? (y/n)" kill-window
bind-key C-x confirm-before -p "kill other windows? (y/n)" "kill-window -a"
bind-key Q confirm-before -p "kill-session #S? (y/n)" kill-session

# Rename session and window
bind-key r command-prompt -I "#W" "rename-window '%%'"
bind-key R command-prompt -I "#S" "rename-session '%%'"
# reload
bind-key C-r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
# open current directory
bind-key o run-shell "open #{pane_current_path}"
bind-key Space run-shell "~/.config/tmux/scripts/toggle_orientation.sh"
# bind-key Space next-layout

source ~/.config/tmux/statusline.conf

# plugins {{{
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

# Plugin config
# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-save-interval '5'

run '~/.config/tmux/plugins/tpm/tpm'
#}}}
